# NOTE: this toml config is a preset overfitting a 9M parameter transformer on 1 image.

[job]
dump_folder = "./outputs"
description = "Debug on a single image."

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = false
save_tb_folder = "tb"

[model]
name = "Llama3-cifar"
flavor = "9M"
hf_assets_path = "./assets/hf/Llama-3-9M"
# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 0.00035
eps = 1e-8
beta1 = 0.95
beta2 = 0.95

[lr_scheduler]
warmup_steps = 100  # lr scheduler warm up
decay_type = "cosine"
min_lr_factor = 0.1

[training]
local_batch_size = 1
seq_len = 3072
max_norm = 1.0  # grad norm clipping
steps = 750
dataset = "cifar-10"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = false
folder = "checkpoint"
interval = 500
last_save_model_only = true
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[compile]
enable=true
components = ["model", "loss"]

[activation_checkpoint]
mode = "none"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[quantize.dense.float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]

[validation]
enable = false
dataset = "cifar-10-validation"
freq = 500
steps = 1200 # Recommend value for c4_validation with world-size=8 and seq_len=8192
